-- Do not edit.  Generated by cheby 1.7.dev0 using these options:
--  --gen-hdl -i axi_lite_dummy.yaml -- Generated on Thu Jul 31 11:18:21 2025 by roessfl


library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity axi_lite_dummy is
  port (
    aclk                 : in    std_logic;
    areset_n             : in    std_logic;
    awvalid              : in    std_logic;
    awready              : out   std_logic;
    awaddr               : in    std_logic_vector(2 downto 2);
    awprot               : in    std_logic_vector(2 downto 0);
    wvalid               : in    std_logic;
    wready               : out   std_logic;
    wdata                : in    std_logic_vector(31 downto 0);
    wstrb                : in    std_logic_vector(3 downto 0);
    bvalid               : out   std_logic;
    bready               : in    std_logic;
    bresp                : out   std_logic_vector(1 downto 0);
    arvalid              : in    std_logic;
    arready              : out   std_logic;
    araddr               : in    std_logic_vector(2 downto 2);
    arprot               : in    std_logic_vector(2 downto 0);
    rvalid               : out   std_logic;
    rready               : in    std_logic;
    rdata                : out   std_logic_vector(31 downto 0);
    rresp                : out   std_logic_vector(1 downto 0);

    -- Counter control
    maxis_control_o      : out   std_logic_vector(31 downto 0);
    maxis_control_wr_o   : out   std_logic;
    maxis_control_rack_i : in    std_logic;

    -- Counter control
    saxis_control_i      : in    std_logic_vector(31 downto 0);
    saxis_control_rd_o   : out   std_logic;
    saxis_control_wack_i : in    std_logic
  );
end axi_lite_dummy;

architecture syn of axi_lite_dummy is
  signal wr_req                         : std_logic;
  signal wr_ack                         : std_logic;
  signal wr_addr                        : std_logic_vector(2 downto 2);
  signal wr_data                        : std_logic_vector(31 downto 0);
  signal axi_awset                      : std_logic;
  signal axi_wset                       : std_logic;
  signal axi_wdone                      : std_logic;
  signal rd_req                         : std_logic;
  signal rd_ack                         : std_logic;
  signal rd_addr                        : std_logic_vector(2 downto 2);
  signal rd_data                        : std_logic_vector(31 downto 0);
  signal axi_arset                      : std_logic;
  signal axi_rdone                      : std_logic;
  signal maxis_control_reg              : std_logic_vector(31 downto 0);
  signal maxis_control_wreq             : std_logic;
  signal maxis_control_wack             : std_logic;
  signal maxis_control_wstrb            : std_logic;
  signal rd_ack_d0                      : std_logic;
  signal rd_dat_d0                      : std_logic_vector(31 downto 0);
  signal wr_req_d0                      : std_logic;
  signal wr_adr_d0                      : std_logic_vector(2 downto 2);
  signal wr_dat_d0                      : std_logic_vector(31 downto 0);
begin

  -- AW, W and B channels
  awready <= not axi_awset;
  wready <= not axi_wset;
  bvalid <= axi_wdone;
  process (aclk) begin
    if rising_edge(aclk) then
      if areset_n = '0' then
        wr_req <= '0';
        axi_awset <= '0';
        axi_wset <= '0';
        axi_wdone <= '0';
      else
        wr_req <= '0';
        if awvalid = '1' and axi_awset = '0' then
          wr_addr <= awaddr;
          axi_awset <= '1';
          wr_req <= axi_wset;
        end if;
        if wvalid = '1' and axi_wset = '0' then
          wr_data <= wdata;
          axi_wset <= '1';
          wr_req <= axi_awset or awvalid;
        end if;
        if (axi_wdone and bready) = '1' then
          axi_wset <= '0';
          axi_awset <= '0';
          axi_wdone <= '0';
        end if;
        if wr_ack = '1' then
          axi_wdone <= '1';
        end if;
      end if;
    end if;
  end process;
  bresp <= "00";

  -- AR and R channels
  arready <= not axi_arset;
  rvalid <= axi_rdone;
  process (aclk) begin
    if rising_edge(aclk) then
      if areset_n = '0' then
        rd_req <= '0';
        axi_arset <= '0';
        axi_rdone <= '0';
        rdata <= (others => '0');
      else
        rd_req <= '0';
        if arvalid = '1' and axi_arset = '0' then
          rd_addr <= araddr;
          axi_arset <= '1';
          rd_req <= '1';
        end if;
        if (axi_rdone and rready) = '1' then
          axi_arset <= '0';
          axi_rdone <= '0';
        end if;
        if rd_ack = '1' then
          axi_rdone <= '1';
          rdata <= rd_data;
        end if;
      end if;
    end if;
  end process;
  rresp <= "00";

  -- pipelining for wr-in+rd-out
  process (aclk) begin
    if rising_edge(aclk) then
      if areset_n = '0' then
        rd_ack <= '0';
        rd_data <= "00000000000000000000000000000000";
        wr_req_d0 <= '0';
        wr_adr_d0 <= "0";
        wr_dat_d0 <= "00000000000000000000000000000000";
      else
        rd_ack <= rd_ack_d0;
        rd_data <= rd_dat_d0;
        wr_req_d0 <= wr_req;
        wr_adr_d0 <= wr_addr;
        wr_dat_d0 <= wr_data;
      end if;
    end if;
  end process;

  -- Register maxis_control
  maxis_control_o <= maxis_control_reg;
  maxis_control_wack <= maxis_control_wreq;
  process (aclk) begin
    if rising_edge(aclk) then
      if areset_n = '0' then
        maxis_control_reg <= "00000000000000000000000000000000";
        maxis_control_wstrb <= '0';
      else
        if maxis_control_wreq = '1' then
          maxis_control_reg <= wr_dat_d0;
        end if;
        maxis_control_wstrb <= maxis_control_wreq;
      end if;
    end if;
  end process;
  maxis_control_wr_o <= maxis_control_wstrb;

  -- Register saxis_control

  -- Process for write requests.
  process (wr_adr_d0, wr_req_d0, maxis_control_wack, saxis_control_wack_i) begin
    maxis_control_wreq <= '0';
    case wr_adr_d0(2 downto 2) is
    when "0" =>
      -- Reg maxis_control
      maxis_control_wreq <= wr_req_d0;
      wr_ack <= maxis_control_wack;
    when "1" =>
      -- Reg saxis_control
      wr_ack <= saxis_control_wack_i;
    when others =>
      wr_ack <= wr_req_d0;
    end case;
  end process;

  -- Process for read requests.
  process (rd_addr, maxis_control_rack_i, rd_req, saxis_control_i) begin
    -- By default ack read requests
    rd_dat_d0 <= (others => 'X');
    saxis_control_rd_o <= '0';
    case rd_addr(2 downto 2) is
    when "0" =>
      -- Reg maxis_control
      rd_ack_d0 <= maxis_control_rack_i;
    when "1" =>
      -- Reg saxis_control
      saxis_control_rd_o <= rd_req;
      rd_ack_d0 <= rd_req;
      rd_dat_d0 <= saxis_control_i;
    when others =>
      rd_ack_d0 <= rd_req;
    end case;
  end process;
end syn;
